
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(364, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setMidLineWidth(0)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.PercentButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("%"))
        self.PercentButton.setGeometry(QtCore.QRect(10, 120, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.PercentButton.setFont(font)
        self.PercentButton.setObjectName("PercentButton")
        self.C_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("C"))
        self.C_Button.setGeometry(QtCore.QRect(100, 120, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.C_Button.setFont(font)
        self.C_Button.setObjectName("C_Button")
        self.ArrowButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.remove_it())
        self.ArrowButton.setGeometry(QtCore.QRect(190, 120, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.ArrowButton.setFont(font)
        self.ArrowButton.setObjectName("ArrowButton")
        self.DivideButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("/"))
        self.DivideButton.setGeometry(QtCore.QRect(280, 120, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.DivideButton.setFont(font)
        self.DivideButton.setObjectName("DivideButton")
        self.Seven_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("7"))
        self.Seven_Button.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Seven_Button.setFont(font)
        self.Seven_Button.setObjectName("Seven_Button")
        self.Eight_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("8"))
        self.Eight_Button.setGeometry(QtCore.QRect(100, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Eight_Button.setFont(font)
        self.Eight_Button.setObjectName("Eight_Button")
        self.Nine_BUtton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("9"))
        self.Nine_BUtton.setGeometry(QtCore.QRect(190, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Nine_BUtton.setFont(font)
        self.Nine_BUtton.setObjectName("Nine_BUtton")
        self.Multiply_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("*"))
        self.Multiply_Button.setGeometry(QtCore.QRect(280, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Multiply_Button.setFont(font)
        self.Multiply_Button.setObjectName("Multiply_Button")
        self.Four_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("4"))
        self.Four_Button.setGeometry(QtCore.QRect(10, 280, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Four_Button.setFont(font)
        self.Four_Button.setObjectName("Four_Button")
        self.Five_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("5"))
        self.Five_Button.setGeometry(QtCore.QRect(100, 280, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Five_Button.setFont(font)
        self.Five_Button.setObjectName("Five_Button")
        self.Six_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("6"))
        self.Six_Button.setGeometry(QtCore.QRect(190, 280, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Six_Button.setFont(font)
        self.Six_Button.setObjectName("Six_Button")
        self.Minus_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("-"))
        self.Minus_Button.setGeometry(QtCore.QRect(280, 280, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Minus_Button.setFont(font)
        self.Minus_Button.setObjectName("Minus_Button")
        self.Three_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("3"))
        self.Three_Button.setGeometry(QtCore.QRect(190, 360, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Three_Button.setFont(font)
        self.Three_Button.setObjectName("Three_Button")
        self.Two_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("2"))
        self.Two_Button.setGeometry(QtCore.QRect(100, 360, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Two_Button.setFont(font)
        self.Two_Button.setObjectName("Two_Button")
        self.One_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("1"))
        self.One_Button.setGeometry(QtCore.QRect(10, 360, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.One_Button.setFont(font)
        self.One_Button.setObjectName("One_Button")
        self.Add_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("+"))
        self.Add_Button.setGeometry(QtCore.QRect(280, 360, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Add_Button.setFont(font)
        self.Add_Button.setObjectName("Add_Button")
        self.Plusminus_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.plus_minus_it())
        self.Plusminus_Button.setGeometry(QtCore.QRect(10, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Plusminus_Button.setFont(font)
        self.Plusminus_Button.setObjectName("Plusminus_Button")
        self.Zero_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("0"))
        self.Zero_Button.setGeometry(QtCore.QRect(100, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Zero_Button.setFont(font)
        self.Zero_Button.setObjectName("Zero_Button")
        self.Equal_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.math_it())
        self.Equal_Button.setGeometry(QtCore.QRect(280, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Equal_Button.setFont(font)
        self.Equal_Button.setObjectName("Equal_Button")
        self.Decimal_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.dot_it())
        self.Decimal_Button.setGeometry(QtCore.QRect(190, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.Decimal_Button.setFont(font)
        self.Decimal_Button.setObjectName("Decimal_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 364, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# #REMOVE CHARACTER
    def remove_it(self):
        #Grab what's on the screen already
        screen = self.outputLabel.text()
        #Remove the last item in list/string
        screen = screen[:-1]
        #Put it back on the screen
        self.outputLabel.setText(screen)

    # let's Do Some math !
    def math_it(self):
        #Grab what's on the screen already
        screen = self.outputLabel.text()
        try:
            answer = eval(screen)
            #Put it back on the screen
            self.outputLabel.setText(str(answer))
        except:
            self.outputLabel.setText("Error")

    # Change from positif/negatif
    def plus_minus_it(self) :
        #Grab what's on the screen already
        screen = self.outputLabel.text()
        if "-" in screen :
            self.outputLabel.setText(screen.replace("-", ""))
        else:
            self.outputLabel.setText(f'-{screen}')

#ADD A DECIMAL
    def dot_it(self):
        screen = self.outputLabel.text() 
        
        if screen[-1] == ".":
            pass
        else: 
            self.outputLabel.setText(f'{screen}.')

    def press_it(self, pressed):
        if pressed == "C":
            self.outputLabel.setText("0")
        else:
            #Check to see if start with 0 and delete 0
            if self.outputLabel.text() == "0" :
                self.outputLabel.setText("")
            #Concatenate the pressed button with what was there allready
            self.outputLabel.setText(f'{self.outputLabel.text()} {pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.PercentButton.setText(_translate("MainWindow", "%"))
        self.C_Button.setText(_translate("MainWindow", "C"))
        self.ArrowButton.setText(_translate("MainWindow", "<<"))
        self.DivideButton.setText(_translate("MainWindow", "/"))
        self.Seven_Button.setText(_translate("MainWindow", "7"))
        self.Nine_BUtton.setText(_translate("MainWindow", "9"))
        self.Eight_Button.setText(_translate("MainWindow", "8"))
        self.Multiply_Button.setText(_translate("MainWindow", "x"))
        self.Four_Button.setText(_translate("MainWindow", "4"))
        self.Three_Button.setText(_translate("MainWindow", "3"))
        self.Two_Button.setText(_translate("MainWindow", "2"))
        self.Six_Button.setText(_translate("MainWindow", "6"))
        self.Five_Button.setText(_translate("MainWindow", "5"))
        self.Minus_Button.setText(_translate("MainWindow", "-"))
        self.One_Button.setText(_translate("MainWindow", "1"))
        self.Add_Button.setText(_translate("MainWindow", "+"))
        self.Plusminus_Button.setText(_translate("MainWindow", "+/-"))
        self.Zero_Button.setText(_translate("MainWindow", "0"))
        self.Equal_Button.setText(_translate("MainWindow", "="))
        self.Decimal_Button.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
